In [4]:
import numpy as np

In [9]:
data=np.random.randint(0,255,(3,3))
data

array([[224, 252, 136],
       [101,   8, 152],
       [234,  98,  92]], dtype=int32)

In [7]:
np.random.rand(3,3)

array([[0.73421052, 0.89814022, 0.88193458],
       [0.70988332, 0.21233706, 0.55592001],
       [0.3053597 , 0.78848172, 0.94373085]])

In [10]:
data=np.random.randint(0,255,(3,3,3))
data

array([[[ 48,  54, 228],
        [162, 182, 141],
        [239, 168,  92]],

       [[113, 119,  43],
        [ 65, 175, 125],
        [198, 129, 208]],

       [[127,  48, 242],
        [223, 213,  87],
        [110, 202, 204]]], dtype=int32)

In [15]:
# arange automatically fetchs values
# range needs the iterator
print(np.arange(1,10,2))
print(np.arange(10,1,-2))
print(range(1,10))


[1 3 5 7 9]
[10  8  6  4  2]
range(1, 10)


In [ ]:
np.linspace(1,10,5) # splits into equal parts 5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# identity
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
data=np.random.randint(1,10,(3,3))# equal parts
print(data)
print(data.shape)
print(data.size)
print(data.ndim) #col,row

[[6 2 4]
 [8 3 1]
 [1 1 6]]
(3, 3)
9
2


In [24]:
#transpose
print(data)
print(data.T)

[[6 2 4]
 [8 3 1]
 [1 1 6]]
[[6 8 1]
 [2 3 1]
 [4 1 6]]


In [ ]:
# indexing---[rows,columns]
#left smallest ,right highest in negative


In [25]:
data1=np.random.randint(1,30,(3,3))
data1

array([[ 1, 26, 12],
       [ 9, 17,  6],
       [ 9, 19,  1]], dtype=int32)

In [33]:
print(data1.mean())
print(data1.sum())
print(data1.min())
print(data1.max())
print(data1.argmin())
print(data1.argmax())
print(data1.argmin(axis=0))#seprate min value in columns
print(data1.argmin(axis=1))#seprate min value in rows
print(data1.argmax(axis=0))#seprate max value in columns
print(data1.argmax(axis=1))#seprate max value in rows

11.11111111111111
100
1
26
0
1
[0 1 2]
[0 2 2]
[1 0 0]
[1 1 1]


In [ ]:
# dot product--multiply  first row * first col....
 #columns and rows should match first then n,..prints

In [34]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [1]:
import numpy as np
data=np.random.randint(0,100,10)
data

array([ 6, 61, 18, 24,  5,  9, 80, 35, 11, 36], dtype=int32)

In [ ]:
#correlation
data1=np.random.randint(0,10,(2,20))
data1

array([[7, 8, 4, 9, 7, 4, 7, 6, 8, 7, 7, 2, 9, 5, 6, 3, 8, 8, 5, 6],
       [7, 0, 2, 8, 7, 8, 1, 3, 9, 2, 3, 6, 6, 3, 9, 5, 7, 7, 4, 0]],
      dtype=int32)

In [4]:
np.corrcoef(data1)

array([[1.        , 0.11835106],
       [0.11835106, 1.        ]])

In [5]:
data1.T

array([[7, 7],
       [8, 0],
       [4, 2],
       [9, 8],
       [7, 7],
       [4, 8],
       [7, 1],
       [6, 3],
       [8, 9],
       [7, 2],
       [7, 3],
       [2, 6],
       [9, 6],
       [5, 3],
       [6, 9],
       [3, 5],
       [8, 7],
       [8, 7],
       [5, 4],
       [6, 0]], dtype=int32)

In [17]:
data=np.array([10,20,30,np.nan,40,50,np.nan])
data

array([10., 20., 30., nan, 40., 50., nan])

In [18]:
print(np.isnan(data))

[False False False  True False False  True]


In [19]:
# null value count
print(np.isnan(data).sum())



2


In [20]:
print(np.nan_to_num(data,nan=0))

[10. 20. 30.  0. 40. 50.  0.]


In [ ]:
# removes null values
print(~np.isnan(data))

[ True  True  True False  True  True False]


In [22]:
print(np.nanmean(data))

30.0


In [23]:
print(np.nanmedian(data))

30.0


In [24]:
print(np.where(np.isnan(data),np.nanmedian(data),data))

[10. 20. 30. 30. 40. 50. 30.]


In [25]:
#np.where(condition, value_if_true, value_if_false)
arr = np.array([10, 15, 20, 25, 30])

# Get indices where elements are greater than 20
indices = np.where(arr > 20)
print(indices) # (array([3, 4]),)

# Replace values: 1 if >20 else 0
binary = np.where(arr > 20, 1, 0)
print(binary) # [0 0 0 1 1]

(array([3, 4]),)
[0 0 0 1 1]


In [26]:
import numpy as np

# Creating array with null values (NaN)
data = np.array([10, 20, np.nan, 40, 50, np.nan, 70])

print("Original Data:", data)
# 1. Detect Null Values
print("Null Positions:", np.isnan(data))
# 2. Count Null Values
print("Total Null Values:", np.isnan(data).sum())
# 3. Remove Null Values
clean_data = data[~np.isnan(data)]
print("After Removing Nulls:", clean_data)
# 4. Replace Null Values with 0
replace_zero = np.nan_to_num(data, nan=0)
print("Replace NaN with 0:", replace_zero)
# 5. Replace Null Values with Mean
mean_value = np.nanmean(data)
replace_mean = np.where(np.isnan(data), mean_value, data)
print("Replace NaN with Mean:", replace_mean)
# 6. Replace Null Values with Median
median_value = np.nanmedian(data)
replace_median = np.where(np.isnan(data), median_value, data)
print("Replace NaN with Median:", replace_median)

# 7. Replace Null Values with Custom Value
replace_custom = np.where(np.isnan(data), 999, data)
print("Replace NaN with Custom Value:", replace_custom)

# 8. Ignore Null Values in Calculations
print("Mean ignoring NaN:", np.nanmean(data))
print("Sum ignoring NaN:", np.nansum(data))
print("Std ignoring NaN:", np.nanstd(data))
print("Min ignoring NaN:", np.nanmin(data))
print("Max ignoring NaN:", np.nanmax(data))

Original Data: [10. 20. nan 40. 50. nan 70.]
Null Positions: [False False  True False False  True False]
Total Null Values: 2
After Removing Nulls: [10. 20. 40. 50. 70.]
Replace NaN with 0: [10. 20.  0. 40. 50.  0. 70.]
Replace NaN with Mean: [10. 20. 38. 40. 50. 38. 70.]
Replace NaN with Median: [10. 20. 40. 40. 50. 40. 70.]
Replace NaN with Custom Value: [ 10.  20. 999.  40.  50. 999.  70.]
Mean ignoring NaN: 38.0
Sum ignoring NaN: 190.0
Std ignoring NaN: 21.354156504062622
Min ignoring NaN: 10.0
Max ignoring NaN: 70.0


In [27]:
# range 
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [28]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [29]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [30]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [32]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [ ]:
np.finfo(np.float64).min # if we want min value

np.float64(-1.7976931348623157e+308)